name: Check branch HEAD

on: [push, pull_request]

jobs:
  check-head:
    name: Check head
    runs-on: ubuntu-latest
    steps:
      - name: Print
        uses: actions/checkout@v2
        run: |
          echo "This branch ultimate commit"
          git rev-parse HEAD
          echo "This branch penultimate commit"
          git rev-parse HEAD^1
          echo "Devepment branch ultimate commit"
          git rev-parse HEAD
