name: Check branch HEAD

on: [push]

jobs:
  check-head:
    name: Check head
    runs-on: ubuntu-latest
    steps:
      #start:git-checkout
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          brach: 'development'
      #end:git-checkout
      - name: Print
        run: |
          echo "This branch ultimate commit"
          git rev-parse HEAD
          echo "This branch penultimate commit"
          git rev-parse HEAD^1
          git checkout development
          echo "Devepment branch ultimate commit"
          git rev-parse HEAD
        shell: bash
