name: Check branch HEAD

on: [push, pull_request]

jobs:
  check-head:
    name: Check head
    runs-on: ubuntu-latest
    steps:
      - name: Console head_ref
        run: echo ${{github.head_ref}}
